# Shared command-line tools
brew "git"
brew "git-lfs"
brew "gh"
brew "git-delta"
brew "mise"
brew "direnv"
brew "autojump"
brew "fzf"
brew "ripgrep"
brew "jq"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "shellcheck"

# Shared applications
cask "ghostty"
cask "zed"
cask "alfred"
cask "rectangle"
cask "hiddenbar"
cask "cleanshot"
cask "fantastical"
cask "readdle-spark"
cask "obsidian"
cask "1password"
cask "1password-cli"
cask "font-commit-mono"
